### ISSUE TITLE
Loading given overlays errors: "OSError: [Errno 22] Invalid argument"

### ISSUE THREAD

**Issue by tafk7** [strath-sdr/RFSoC-Book#3]
Attempting to use this on a ZCU111 consistently gives the opaque error in the title when trying to load any of the overlays, specifically when attempting to write the binfile_name. I the following error from Notebook A's [04_overlays.ipnyb](https://github.com/strath-sdr/RFSoC-Book/blob/main/rfsoc_book/notebooks/notebook_A/04_overlays.ipynb).

Running:
```
from pynq_nco.overlay import NumericalOverlay

ol = NumericalOverlay()
```

Gives:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-1-6c791a2f05e3> in <module>
      1 from pynq_nco.overlay import NumericalOverlay
      2 
----> 3 ol = NumericalOverlay()

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq_nco/overlay.py in __init__(self, bitfile_name, **kwargs)
     13             bitfile_name = os.path.join(this_dir, 'bitstream', 'pynq_nco.bit')
     14 
---> 15         super().__init__(bitfile_name, **kwargs)

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/overlay.py in __init__(self, bitfile_name, dtbo, download, ignore_version, device)
    352 
    353         if download:
--> 354             self.download()
    355 
    356         self.__doc__ = _build_docstring(self._ip_map._description,

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/overlay.py in download(self, dtbo)
    418                     Clocks.set_pl_clk(i)
    419 
--> 420         super().download(self.parser)
    421         if dtbo:
    422             super().insert_dtbo(dtbo)

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/bitstream.py in download(self, parser)
    185 
    186         """
--> 187         self.device.download(self, parser)
    188 
    189     def remove_dtbo(self):

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/pl_server/embedded_device.py in download(self, bitstream, parser)
    594             fd.write(str(flag))
    595         with open(self.BS_FPGA_MAN, 'w') as fd:
--> 596             fd.write(bitstream.binfile_name)
    597 
    598         self.set_axi_port_width(parser)

OSError: [Errno 22] Invalid argument

```

I get the same error when attempting to load any of the provided overlays in any of the notebooks (such as RadioOverlay [here](https://github.com/strath-sdr/RFSoC-Book/blob/main/rfsoc_book/notebooks/notebook_G/02_rfsoc_radio_observe.ipynb)) and when trying to load the Overlays using the hard path and the standard pynq Overlay function.

I've been pretty stumped on this for a while and would greatly appreciate any advice.

**Comment by dnorthcote** [comment]
Hi @Rellek72 

I'm sorry that you have had a few issues. I'll try and fix them for you.

Are you able to answer the questions below:

- Can you confirm the version of PYNQ that you are using?
- Did you build this version of PYNQ on your own, or are you using the prebuilt images located [here](https://github.com/Xilinx/PYNQ/releases/tag/v2.7.0)?
- Are you using a fresh build of PYNQ that has not been modified and is newly written to an SD Card?
- Can you give me the ZCU111 board revision? It will be on the board, usually on the silkscreen or a white label.
- Were there any notable errors in the command window when you installed the RFSoC-Book files on your PYNQ platform?

I'm sure we'll get to the bottom of the problem, and apologies again for any inconvenience,

Thanks,
David.

**Comment by tafk7** [comment]
Thank you so much for the prompt and detailed reply!

I am running 2.7, which I downloaded from [here](http://www.pynq.io/board.html). The board revision is Version 1.0. I didn't see any significant errors from installation (just reinstalled to confirm).

**Comment by tafk7** [comment]
Accidental close

**Comment by dnorthcote** [comment]
Hi @Rellek72 

Are you able to download and install a fresh version of PYNQ v2.7 from here: https://bit.ly/zcu111_2_7 

Then launch PYNQ on the ZCU111 and run the following for me in a terminal window in Jupyter.

* Start by changing the directory.
  * `cd /home/xilinx/jupyter_notebooks`
* Now, create a log of the installed Python modules.
  * `pip list | tee -a pip_list.txt`
* Pip install RFSoC-Book and create another log.
  * `pip install https://github.com/strath-sdr/RFSoC-Book/archive/v1.0.1.tar.gz | tee -a pip_log.txt`
* Lastly, install the book notebooks and packages and create a new log.
  * `python -m rfsoc_book install | tee -a install_log.txt`

Can you send the outputs of each log file to me. They will be in the Jupyter workspace directory on the left-hand pane.

Thanks again for your patience here. We have been unable to replicate your issue on our ZCU111, so perhaps something has failed during installation,

Kind regards,
David.

**Comment by tafk7** [comment]
Here are the requested logs. The image you provided is a bit smaller than the one I was using so it might be different, however after installing as you described I still get the same error. 

[pip_list.txt](https://github.com/strath-sdr/RFSoC-Book/files/10934492/pip_list.txt)
[install_log.txt](https://github.com/strath-sdr/RFSoC-Book/files/10934493/install_log.txt)
[pip_log.txt](https://github.com/strath-sdr/RFSoC-Book/files/10934494/pip_log.txt)

Thank you again for your detailed and thorough assistance.

**Comment by dnorthcote** [comment]
Hi @Rellek72 

Looking at the logs it appears that there are no issues, which is strange.

The PYNQ images should be the same size as they are actually downloaded from the same location. If you look at the location you gave us here http://www.pynq.io/board.html, and then hover over v2.7 for the ZCU111, it will reveal the same link I provided you above.

If the file sizes are different then there is more than one issue we need to resolve.

With all of the above executed in my previous post, can you now run the spectrum analyser? This will be notebook C: 01_exploring_the_spectrum.ipynb.

Once you have ran the spectrum analyser, please let me know the outcome by saving the Jupyter notebook and posting it here just like you did with the log files.

Thanks,
David.

**Comment by tafk7** [comment]
Running the spectrum analyzer gives the same error on the initial Overlay assignment (file changed to txt so github accepts it):
[01_exploring_the_spectrum.ipynb.txt](https://github.com/strath-sdr/RFSoC-Book/files/10935219/01_exploring_the_spectrum.ipynb.txt)

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-1-cdf4de6f148d> in <module>
      1 from rfsoc_sam.overlay import Overlay
      2 
----> 3 sam = Overlay()

/usr/local/share/pynq-venv/lib/python3.8/site-packages/rfsoc_sam/overlay.py in __init__(self, overlay_system, init_rf_clks, **kwargs)
     60             raise ValueError(''.join(["Unknown overlay design ", overlay_system]))
     61 
---> 62         super().__init__(bitfile_name, **kwargs)
     63 
     64         if init_rf_clks:

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/overlay.py in __init__(self, bitfile_name, dtbo, download, ignore_version, device)
    352 
    353         if download:
--> 354             self.download()
    355 
    356         self.__doc__ = _build_docstring(self._ip_map._description,

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/overlay.py in download(self, dtbo)
    418                     Clocks.set_pl_clk(i)
    419 
--> 420         super().download(self.parser)
    421         if dtbo:
    422             super().insert_dtbo(dtbo)

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/bitstream.py in download(self, parser)
    185 
    186         """
--> 187         self.device.download(self, parser)
    188 
    189     def remove_dtbo(self):

/usr/local/share/pynq-venv/lib/python3.8/site-packages/pynq/pl_server/embedded_device.py in download(self, bitstream, parser)
    594             fd.write(str(flag))
    595         with open(self.BS_FPGA_MAN, 'w') as fd:
--> 596             fd.write(bitstream.binfile_name)
    597 
    598         self.set_axi_port_width(parser)

OSError: [Errno 22] Invalid argument
```

Would it be possible to see a picture of the board you're running on to ensure that my pin layouts are the same? Although I'm fairly certain mine are correct, it's the only other thing I can really think of. 

As for the file size, perhaps I had accidentally downloaded the wrong image previously. Regardless, I'm certain that it's currently running on the correct v2.7 image for the ZCU111.

**Comment by dnorthcote** [comment]
Hi @Rellek72 

My colleague and I have almost exhausted our ideas on what could be wrong, but we still have a few suggestions left.

Look at this PYNQ post, which has the same issue as you: https://discuss.pynq.io/t/can-not-download-the-bit-from-the-kv260/4601.

You will be able to see that the final solution is "Please make sure the FPGA device is aligned with the project."

This tells me that the FPGA part selected by the person in the post was wrong, although it is unclear what the final solution was.

We have sent over our usual board setup. I don't have access to the board, so I can't give a more precise image at this time.

Let me know if the jumpers solve your issue, and we will think over what the solution could be,

Thanks,
David.

<img width="1000" alt="rfsoc_zcu111" src="https://user-images.githubusercontent.com/42978178/224136064-f78d2789-5adc-4890-8db2-466ea16bff91.png">

**Comment by dnorthcote** [comment]
Hi @Rellek72 

This post here also suggests the wrong part is being used and is related to the error you see. https://discuss.pynq.io/t/cant-download-bitstream/3690

Can you send me a photograph of the board you are using?

Thanks again,
David.

**Comment by tafk7** [comment]
![20230309_135514](https://user-images.githubusercontent.com/6666644/224162631-ab53c7f4-49b0-4b7a-8732-b521bb6a7524.jpg)

**Comment by dnorthcote** [comment]
Hi @Rellek72 

We want to test whether your problem is related to the work in this repository.

Can you install and test the DSP PYNQ module using a fresh image of PYNQ v2.7? This module has been around as long as RFSoC-PYNQ. It should work fine on any supported board. You can install it using the following command:

`pip3 install https://github.com/Xilinx/DSP-PYNQ/releases/download/v3.1/dsp_pynq-3.1.tar.gz`

Now, try and use the second notebook located in the dsp_pynq folder that has appeared in the Jupyter workspace. It should be named: 02_dsp_and_pynq.ipynb.

Kind regards,
David.

**Comment by tafk7** [comment]
Apologies for the delayed response. Attempting to run the above gives the same error at the overlay... I suppose something must just be seriously wrong with my board. Thank you for your time and assistance.

**Comment by dnorthcote** [comment]
Hi @Rellek72 

I think taking this issue to the [pynq.io](https://discuss.pynq.io/) support forms would be a good idea to see if the PYNQ team can shed light on what is happening here. I must admit; I am a little confused about why this is occurring and, unfortunately, out of ideas.

I think it would be a good idea to mention you tried the above test with DSP-PYNQ and experiencing issues with overlay download. Include the appropriate error dialogue, the board version and type, and the PYNQ version you are running.

Thanks,
David.
