### ISSUE TITLE
PYNQ_Image for zcu216 Board

### ISSUE THREAD

**Issue by Alsbirij** [strath-sdr/RFSoC-Book#8]
I just bought the Book and i already have the Board zcu216.
the board is mentioned multiple times in the Book but there does not seem to be a prebuilt image for it.
is there a prebuilt image, it would be nice if you can share it ?
If there is no image, is it possible to custimize one and what are the detailed steps to do it ?

**Comment by axdy** [comment]
Hi there,

You can find a PYNQ 2.7 image for ZCU216 on the following repo issue from the QICK team: https://github.com/sarafs1926/ZCU216-PYNQ/issues/1

Hope that helps!
Andrew
